import type { DashboardState, Extension, Group } from "../src/models";

const groupColors = {
  aiCoding: "#7C3AED",
  pythonData: "#2563EB",
  webDevelopment: "#D97706",
  writing: "#059669",
} as const;

const groups: Group[] = [
  { id: "ai-coding", name: "AI Coding", color: groupColors.aiCoding },
  { id: "python-data", name: "Python & Data", color: groupColors.pythonData },
  { id: "web-development", name: "Web Development", color: groupColors.webDevelopment },
  { id: "writing", name: "Writing", color: groupColors.writing },
];

const extensions: Extension[] = [
  {
    id: "openai.codex",
    name: "Codex",
    publisher: "OpenAI",
    description: "AI coding assistant for exploring and editing your project.",
    version: "1.0.0",
    groupId: "ai-coding",
    visibility: "Visible",
    monogram: "C",
    color: groupColors.aiCoding,
    tags: ["AI", "Coding"],
  },
  {
    id: "anthropic.claude-code",
    name: "Claude Code",
    publisher: "Anthropic",
    description: "Agentic coding assistance in the editor.",
    version: "1.2.0",
    groupId: "ai-coding",
    visibility: "Visible",
    monogram: "C",
    color: groupColors.aiCoding,
    tags: ["AI", "Coding"],
  },
  {
    id: "github.copilot",
    name: "GitHub Copilot",
    publisher: "GitHub",
    description: "AI pair programmer with inline suggestions and chat.",
    version: "1.250.0",
    groupId: "ai-coding",
    visibility: "Visible",
    monogram: "C",
    color: groupColors.aiCoding,
    tags: ["AI", "Coding"],
  },
  {
    id: "ms-python.python",
    name: "Python",
    publisher: "Microsoft",
    description: "Rich support for the Python language.",
    version: "2024.20.0",
    groupId: "python-data",
    visibility: "Visible",
    monogram: "P",
    color: groupColors.pythonData,
    tags: ["Python", "Language"],
  },
  {
    id: "ms-python.vscode-pylance",
    name: "Pylance",
    publisher: "Microsoft",
    description: "Fast, feature-rich language support for Python.",
    version: "2024.10.1",
    groupId: "python-data",
    visibility: "Visible",
    monogram: "P",
    color: groupColors.pythonData,
    tags: ["Python", "Language"],
  },
  {
    id: "ms-toolsai.jupyter",
    name: "Jupyter",
    publisher: "Microsoft",
    description: "Notebook support for interactive data science workflows.",
    version: "2024.9.0",
    groupId: "python-data",
    visibility: "Visible",
    monogram: "J",
    color: groupColors.pythonData,
    tags: ["Python", "Data"],
  },
  {
    id: "charliermarsh.ruff",
    name: "Ruff",
    publisher: "Astral Software",
    description: "Extremely fast Python linter and formatter.",
    version: "2024.40.0",
    groupId: "python-data",
    visibility: "NotVisible",
    monogram: "RF",
    color: groupColors.pythonData,
    tags: ["Python", "Quality"],
  },
  {
    id: "dbaeumer.vscode-eslint",
    name: "ESLint",
    publisher: "Microsoft",
    description: "Integrates ESLint into Visual Studio Code.",
    version: "3.0.10",
    groupId: "web-development",
    visibility: "NotVisible",
    monogram: "ES",
    color: groupColors.webDevelopment,
    tags: ["JavaScript", "Quality"],
  },
  {
    id: "esbenp.prettier-vscode",
    name: "Prettier",
    publisher: "Prettier",
    description: "Code formatter using prettier.",
    version: "11.0.0",
    groupId: "web-development",
    visibility: "Visible",
    monogram: "PR",
    color: groupColors.webDevelopment,
    tags: ["JavaScript", "Formatting"],
  },
  {
    id: "eamodio.gitlens",
    name: "GitLens",
    publisher: "GitKraken",
    description: "Supercharge Git inside Visual Studio Code.",
    version: "15.5.0",
    groupId: "web-development",
    visibility: "Visible",
    monogram: "GL",
    color: groupColors.webDevelopment,
    tags: ["Git"],
  },
  {
    id: "james-yu.latex-workshop",
    name: "LaTeX Workshop",
    publisher: "James Yu",
    description: "Boost LaTeX typesetting efficiency with Visual Studio Code.",
    version: "10.5.0",
    groupId: "writing",
    visibility: "Visible",
    monogram: "LW",
    color: groupColors.writing,
    tags: ["Writing", "LaTeX"],
  },
  {
    id: "yzhang.markdown-all-in-one",
    name: "Markdown All in One",
    publisher: "Yu Zhang",
    description: "All you need for Markdown in one place.",
    version: "3.6.2",
    groupId: "writing",
    visibility: "Visible",
    monogram: "MD",
    color: groupColors.writing,
    tags: ["Writing", "Markdown"],
  },
  {
    id: "mechatroner.rainbow-csv",
    name: "Rainbow CSV",
    publisher: "Mechatroner",
    description: "Highlight columns in CSV and TSV files.",
    version: "3.12.0",
    groupId: null,
    visibility: "Visible",
    monogram: "RC",
    color: "#DB2777",
    tags: ["Data", "CSV"],
  },
  {
    id: "pkief.material-icon-theme",
    name: "Material Icon Theme",
    publisher: "Philipp Kief",
    description: "Material Design icons for Visual Studio Code.",
    version: "5.8.0",
    groupId: null,
    visibility: "NotVisible",
    monogram: "MI",
    color: "#0EA5E9",
    tags: ["Theme"],
  },
];


/** 演示初始状态；状态操作会通过副本使用这份数据。 */
export const seedState: DashboardState = {
  schemaVersion: 1,
  groups,
  extensions: [...extensions].sort((a, b) => a.name.localeCompare(b.name) || a.id.localeCompare(b.id)),
};
