import { useEffect, useState } from 'react';
import { Layers, Plus, RefreshCw, Info, Check, FolderInput, Trash2, Pencil, ArrowDownUp } from 'lucide-react';
import type { Action, DemoState } from './models';
import { loadState, reducer, saveState, validateState } from './state';
import { seedState } from './seed';
import Modal from './Modal';
import { showNativeGroups } from './Sidebar';
import ExtensionCards from './ExtensionCards';

type HostApi={postMessage:(message:unknown)=>void};
declare global { interface Window { acquireVsCodeApi?:()=>HostApi } }
const host=window.acquireVsCodeApi?.();
type DialogState={kind:'create'|'rename'|'deleteGroup'|'uninstall'|'reset'|'move'|'details'|'transfer'|'groups';id?:string};
/** Dashboard 使用宿主快照；浏览器仅供独立组件验证，不模拟原生侧边栏。 */
export default function App(){
 const [state,setState]=useState<DemoState>(()=>host?structuredClone(seedState):loadState());
 const [group,setGroup]=useState('all');const [status,setStatus]=useState('all');const [query,setQuery]=useState('');
 const [selected,setSelected]=useState<string[]>([]);const [menu,setMenu]=useState<string|null>(null);const [dialog,setDialog]=useState<DialogState|null>(null);
 const [name,setName]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [saved,setSaved]=useState(true);const [ready,setReady]=useState(!host);
 useEffect(()=>{if(!host)return;const listener=(e:MessageEvent)=>{if(!e.data||typeof e.data!=='object')return;if(e.data.type==='state'&&validateState(e.data.state)){setState(e.data.state);setSelected(ids=>ids.filter(id=>e.data.state.extensions.some((x:{id:string})=>x.id===id)));setGroup(id=>id==="all"||id==="ungrouped"||e.data.state.groups.some((g:{id:string})=>g.id===id)?id:"all");setDialog(d=>d?.id&&!e.data.state.extensions.some((x:{id:string})=>x.id===d.id)&&!e.data.state.groups.some((g:{id:string})=>g.id===d.id)?null:d);setReady(true);setSaved(true)}if(e.data.type==='filter'&&typeof e.data.groupId==='string'){setGroup(e.data.groupId);setStatus('all');setQuery('')}if(e.data.type==='error'){setNotice(String(e.data.message));setSaved(false)}};window.addEventListener('message',listener);host.postMessage({type:'ready'});return()=>window.removeEventListener('message',listener)},[]);
 useEffect(()=>{if(host)return;setSaved(saveState(state))},[state]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(!(e.target as HTMLElement).closest('.context-menu,.row-actions'))setMenu(null)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 /** 派发动作至真实扩展宿主；验证预览仅更新本地示例状态。 */
 function dispatch(action:Action){if(host){host.postMessage({type:'action',action})}else{setState(s=>reducer(s,action))}setMenu(null)}
 function open(d:DialogState){setDialog(d);setMenu(null);setError('');setName(d.kind==='rename'?state.groups.find(g=>g.id===d.id)?.name??'':'')}
 function toggle(id:string){dispatch({type:'toggle',id});setNotice(host?'Status change requested':'Status updated')}
 function update(id:string){dispatch({type:'update',id});setNotice('Demo update requested')}
 function move(ids:string[],id:string|null){dispatch({type:'move',ids,groupId:id});setSelected([]);setDialog(null);setNotice(`${host?"Move requested for":"Moved"} ${ids.length} extension${ids.length===1?'':'s'} to ${state.groups.find(g=>g.id===id)?.name??'Ungrouped'}.`)}
 function submitName(e:React.FormEvent){e.preventDefault();const value=name.trim();if(!value||Array.from(value).length>50||value.toLowerCase()==='ungrouped'||state.groups.some(g=>g.id!==dialog?.id&&g.name.toLowerCase()===value.toLowerCase())){setError('Use a unique group name between 1 and 50 characters.');return}dispatch(dialog?.kind==='rename'?{type:'renameGroup',id:dialog.id!,name:value}:{type:'createGroup',name:value});setDialog(null)}
 async function copy(id:string){try{await navigator.clipboard.writeText(id);setNotice('Extension ID copied.')}catch{setNotice(`Extension ID: ${id}`)}setMenu(null)}
 function exportData(){if(host){host.postMessage({type:'export'});return}const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='extension-nest-demo.json';a.click();URL.revokeObjectURL(url)}
 const rows=state.extensions.filter(e=>(group==='all'||(group==='ungrouped'?e.groupId===null:e.groupId===group))&&(status==='all'||(status==='enabled'?e.enabled:status==='disabled'?!e.enabled:!!e.update))&&`${e.name} ${e.publisher} ${e.id}`.toLowerCase().includes(query.toLowerCase()));
 const metrics=[['Installed',state.extensions.length,'all'],['Enabled',state.extensions.filter(e=>e.enabled).length,'enabled'],['Disabled',state.extensions.filter(e=>!e.enabled).length,'disabled'],['Updates',state.extensions.filter(e=>e.update).length,'updates'],['Ungrouped',state.extensions.filter(e=>!e.groupId).length,'ungrouped']] as const;
 const ext=state.extensions.find(e=>e.id===dialog?.id);const activeGroup=state.groups.find(g=>g.id===group);
 return <div className="app" onKeyDown={e=>{if(e.key==='Escape')setMenu(null)}}><main><header className="compact-header"><h1>Extensions</h1><div className="header-actions"><button onClick={()=>setNotice(`${state.extensions.filter(e=>e.update).length} demo updates`)}><RefreshCw size={14}/>Check updates</button><button onClick={()=>open({kind:'create'})}><Plus size={15}/>Group</button></div></header>
 <section className="metrics" aria-label="Extension overview">{metrics.map(([label,count,key])=><button key={key} className={`metric ${(status===key&&key!=='all')||(group==='ungrouped'&&key==='ungrouped')?'metric-active':''}`} onClick={()=>{setGroup(key==='ungrouped'?'ungrouped':'all');setStatus(key==='ungrouped'?'all':key);setQuery('');setSelected([])}}><span>{label}</span><strong>{count}</strong></button>)}</section>
 <section aria-label="Installed extensions"><div className="list-toolbar"><h2>{activeGroup?.name??(group==='ungrouped'?'Ungrouped':'All extensions')}<small>{rows.length}</small></h2><div className="filters"><input id="search" aria-label="Search extensions" placeholder="Search..." value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter group" value={group} onChange={e=>{setGroup(e.target.value);setSelected([])}}><option value="all">All groups</option>{state.groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}<option value="ungrouped">Ungrouped</option></select><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All status</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option><option value="updates">Updates</option></select></div></div>
 {(query||group!=='all'||status!=='all'||selected.length>0)&&<div className="selection-bar"><span>{selected.length?`${selected.length} selected`:'Filtered view'}</span>{selected.length>0&&<button onClick={()=>open({kind:'move'})}><FolderInput size={15}/>Move to group</button>}<button onClick={()=>{setGroup('all');setStatus('all');setQuery('');setSelected([])}}>Clear</button></div>}
 <div><ExtensionCards rows={rows} groups={state.groups} selected={selected} onSelect={setSelected} menu={menu} onMenu={setMenu} onToggle={toggle} onUpdate={update} onDelete={id=>open({kind:'uninstall',id})} onMove={id=>open({kind:'move',id})} onDetail={id=>open({kind:'details',id})} onCopy={copy}/></div>
 </section></main>
 <footer><span><Info size={16}/>Demo · Sample data</span><div><button onClick={()=>open({kind:'transfer'})}>Import / Export</button><button onClick={()=>open({kind:'reset'})}>Reset demo</button><span className={saved?'saved':'danger-text'}><Check size={17}/>{!ready?'Connecting…':saved?(host?'Saved':'Saved'):'Save failed'}</span></div></footer>
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
 {dialog&&<Modal title={dialog.kind==='create'?'New group':dialog.kind==='rename'?'Rename group':dialog.kind==='deleteGroup'?'Delete group?':dialog.kind==='uninstall'?`Uninstall ${ext?.name}?`:dialog.kind==='reset'?'Reset demo?':dialog.kind==='move'?'Move to group':dialog.kind==='details'?ext?.name??'Extension':dialog.kind==='groups'?'Manage groups':'Import / Export'} onClose={()=>setDialog(null)}>
 {(dialog.kind==='create'||dialog.kind==='rename')&&<form onSubmit={submitName}><label>Group name<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Research"/></label>{error&&<p className="danger-text" role="alert">{error}</p>}<div className="modal-actions"><button type="button" onClick={()=>setDialog(null)}>Cancel</button><button className="primary">{dialog.kind==='create'?'Create group':'Save name'}</button></div></form>}
 {dialog.kind==='move'&&<div className="choices"><p>Move {dialog.id?ext?.name:`${selected.length} extensions`} to one group. The previous group will be replaced.</p>{[...state.groups,{id:'ungrouped',name:'Ungrouped'}].map(g=><button key={g.id} onClick={()=>move(dialog.id?[dialog.id]:selected,g.id==='ungrouped'?null:g.id)}><FolderInput size={17}/>{g.name}</button>)}</div>}
 {['deleteGroup','uninstall','reset'].includes(dialog.kind)&&<><p>{dialog.kind==='deleteGroup'?'Extensions in this group will become ungrouped. Nothing is uninstalled.':dialog.kind==='uninstall'?'This only removes the sample extension from this demo. Your real VS Code extensions are unchanged.':'Restore the 14 sample extensions and original groups. Your demo changes will be replaced.'}</p><div className="modal-actions"><button onClick={()=>setDialog(null)}>Cancel</button><button className="danger" onClick={()=>{dispatch(dialog.kind==='reset'?{type:'reset'}:dialog.kind==='deleteGroup'?{type:'deleteGroup',id:dialog.id!}:{type:'uninstall',id:dialog.id!});setDialog(null);setSelected([]);setGroup('all');setNotice('Demo data updated.')}}>{dialog.kind==='reset'?'Reset demo':dialog.kind==='deleteGroup'?'Delete group':'Uninstall sample'}</button></div></>}
 {dialog.kind==='details'&&ext&&<><p>{ext.description}</p><dl><dt>Extension ID</dt><dd>{ext.id}</dd><dt>Version</dt><dd>{ext.version}{ext.update?` → ${ext.update} available`:''}</dd><dt>Group</dt><dd>{state.groups.find(g=>g.id===ext.groupId)?.name??'Ungrouped'}</dd><dt>Status</dt><dd>{ext.enabled?'Enabled':'Disabled'} · Local demo</dd></dl><p className="muted">Sample metadata. This demo does not connect to Marketplace.</p><div className="modal-actions"><button onClick={()=>copy(ext.id)}>Copy ID</button><button className="primary" onClick={()=>{toggle(ext.id);setDialog(null)}}>{ext.enabled?'Disable sample':'Enable sample'}</button></div></>}
 {dialog.kind==='transfer'&&<div className="choices"><p>Back up or restore the demo state. Imports replace your demo groups and sample extensions.</p><button onClick={exportData}><ArrowDownUp size={17}/>Export demo JSON</button>{host?<button onClick={()=>host.postMessage({type:'importFile'})}>Import demo JSON…</button>:<label className="file-input">Import demo JSON<input type="file" accept="application/json,.json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>1000000)throw Error('File exceeds 1 MB.');const value=JSON.parse(await file.text());if(!validateState(value))throw Error('Invalid demo file.');if(window.confirm('Replace the current demo state?')){setState(value);setGroup('all');setSelected([]);setDialog(null)}}catch(error){setError(error instanceof Error?error.message:'Import failed')}}}/></label>}{error&&<p role="alert" className="danger-text">{error}</p>}</div>}
 {dialog.kind==='groups'&&<div className="choices"><p>In VS Code, these groups live in the native Explorer sidebar.</p>{state.groups.map(g=><div className="manage-row" key={g.id}><span>{g.name}</span><button aria-label={`Rename ${g.name}`} className="icon-button" onClick={()=>open({kind:'rename',id:g.id})}><Pencil size={16}/></button><button aria-label={`Delete ${g.name}`} className="icon-button" onClick={()=>open({kind:'deleteGroup',id:g.id})}><Trash2 size={16}/></button></div>)}</div>}
 </Modal>}</div>
}
