import { MoreHorizontal, ArrowUp, Power, Trash2, FolderInput, Info, Copy } from 'lucide-react';
import type { Extension, Group } from './models';
interface Props { rows:Extension[]; groups:Group[]; selected:string[]; onSelect:(ids:string[])=>void; menu:string|null; onMenu:(id:string|null)=>void; onToggle:(id:string)=>void; onUpdate:(id:string)=>void; onDelete:(id:string)=>void; onMove:(id:string)=>void; onDetail:(id:string)=>void; onCopy:(id:string)=>void }
/** 以紧凑卡片展示插件，保留鼠标选择、移组和管理操作。 */
export default function ExtensionCards(p:Props) {
 const all=p.rows.length>0&&p.rows.every(e=>p.selected.includes(e.id));
 return <div className="cards-region"><label className="select-all"><input type="checkbox" aria-label="Select all visible extensions" checked={all} onChange={()=>p.onSelect(all?p.selected.filter(id=>!p.rows.some(e=>e.id===id)):[...new Set([...p.selected,...p.rows.map(e=>e.id)])])}/>Select all</label>
 <div className="extension-grid">{p.rows.map(ext=><article key={ext.id} data-extension={ext.id} aria-label={ext.name} className={`extension-card ${!ext.enabled?'is-disabled':''} ${p.selected.includes(ext.id)?'selected':''} ${p.menu===ext.id?'menu-open':''}`} onContextMenu={e=>{e.preventDefault();p.onMenu(ext.id)}}>
 <div className="card-heading"><input type="checkbox" aria-label={`Select ${ext.name}`} checked={p.selected.includes(ext.id)} onChange={()=>p.onSelect(p.selected.includes(ext.id)?p.selected.filter(id=>id!==ext.id):[...p.selected,ext.id])}/><button className="extension-name" onClick={()=>p.onDetail(ext.id)}><span className="monogram" style={{background:ext.color}}>{ext.monogram}</span><span><strong title={ext.name}>{ext.name}</strong><small>{ext.publisher}</small></span></button><div className="row-actions"><button className="icon-button" aria-label={`Manage ${ext.name}`} aria-expanded={p.menu===ext.id} onClick={()=>p.onMenu(p.menu===ext.id?null:ext.id)}><MoreHorizontal size={18}/></button>
 {p.menu===ext.id&&<div className="context-menu" role="menu" aria-label={`${ext.name} actions`}><button role="menuitem" onClick={()=>p.onDetail(ext.id)}><Info size={14}/>Details</button><button role="menuitem" onClick={()=>p.onMove(ext.id)}><FolderInput size={14}/>Move to group</button><button role="menuitem" onClick={()=>p.onToggle(ext.id)}><Power size={14}/>{ext.enabled?'Disable':'Enable'}</button>{ext.update&&<button role="menuitem" onClick={()=>p.onUpdate(ext.id)}><ArrowUp size={14}/>Update</button>}<button role="menuitem" onClick={()=>p.onCopy(ext.id)}><Copy size={14}/>Copy ID</button><button role="menuitem" className="danger-text" onClick={()=>p.onDelete(ext.id)}><Trash2 size={14}/>Uninstall…</button></div>}</div></div>
 <div className="card-meta"><button className="group-cell" title="Move to group" onClick={()=>p.onMove(ext.id)}><FolderInput size={13}/>{p.groups.find(g=>g.id===ext.groupId)?.name??'Ungrouped'}</button><span className="version">{ext.version}</span></div>
 <div className="card-bottom"><button className={`status ${ext.enabled?'enabled':''}`} aria-label={`${ext.enabled?'Disable':'Enable'} ${ext.name}`} onClick={()=>p.onToggle(ext.id)}><i/>{ext.enabled?'Enabled':'Disabled'}</button>{ext.update&&<button className="update" aria-label={`Update ${ext.name}`} onClick={()=>p.onUpdate(ext.id)}><ArrowUp size={13}/>Update</button>}</div>
 </article>)}</div>{p.rows.length===0&&<div className="empty">No extensions</div>}</div>
}
