import { MoreHorizontal, ArrowUp, Power, Tag, FolderInput, Info, Copy } from 'lucide-react';
import type { CSSProperties } from 'react';
import type { Extension, Group } from './models';
import { groupExtensions } from './groupExtensions';
import { groupCssColor } from './groupColors';
import { useCardDrag } from './useCardDrag';
import { EXTENSION_DRAG_MIME, parseDraggedIds } from './dragPayload';
interface Props { activeGroup:string; filtered:boolean; rows:Extension[]; groups:Group[]; selected:string[]; onSelect:(ids:string[])=>void; onDropExtensions:(ids:string[],groupId:string|null)=>void; menu:string|null; onMenu:(id:string|null)=>void; onToggle:(id:string)=>void; onUpdate:(id:string)=>void; onEditTags:(id:string)=>void; onFilterTag:(tag:string)=>void; onMove:(id:string)=>void; onDetail:(id:string)=>void; onCopy:(id:string)=>void }
/** 以紧凑卡片展示插件，保留鼠标选择、移组和管理操作。 */
export default function ExtensionCards(p:Props) {
 const drag=useCardDrag(p.onDropExtensions,()=>p.onMenu(null));
 const sections=groupExtensions(p.groups,p.rows,p.activeGroup,p.filtered);
 const all=p.rows.length>0&&p.rows.every(e=>p.selected.includes(e.id));
 const groupStyle=(id:string)=>({'--group-color':groupCssColor(p.groups.find(group=>group.id===id)?.color)} as CSSProperties);
 return <div className="cards-region"><label className="select-all"><input type="checkbox" aria-label="Select all visible extensions" checked={all} onChange={()=>p.onSelect(all?p.selected.filter(id=>!p.rows.some(e=>e.id===id)):[...new Set([...p.selected,...p.rows.map(e=>e.id)])])}/>Select all</label>
 {sections.map(section=><details className={`extension-section${drag.targetGroup===section.id?' is-drop-target':''}`} style={groupStyle(section.id)} key={section.id} open data-group-section={section.id}
 onDragOver={event=>{if(Array.from(event.dataTransfer.types).includes(EXTENSION_DRAG_MIME)){event.preventDefault();event.dataTransfer.dropEffect='move'}}}
 onDrop={event=>{event.preventDefault();event.stopPropagation();const ids=parseDraggedIds(event.dataTransfer.getData(EXTENSION_DRAG_MIME));if(ids)p.onDropExtensions(ids,section.id==='ungrouped'?null:section.id)}}><summary><span>{section.name}</span><small>{section.extensions.length}</small></summary><div className="extension-grid">{section.extensions.map(ext=><article key={ext.id} data-extension={ext.id} aria-label={ext.name} draggable={false} onDragStart={event=>event.preventDefault()}
 style={groupStyle(section.id)} onPointerDown={event=>drag.begin(event,p.selected.includes(ext.id)?p.selected:[ext.id])} className={`extension-card ${drag.activeIds.includes(ext.id)?'is-dragging':''} ${!ext.enabled?'is-disabled':''} ${p.selected.includes(ext.id)?'selected':''} ${p.menu===ext.id?'menu-open':''}`} onContextMenu={e=>{e.preventDefault();p.onMenu(ext.id)}}>
 <div className="card-heading"><input type="checkbox" aria-label={`Select ${ext.name}`} checked={p.selected.includes(ext.id)} onChange={()=>p.onSelect(p.selected.includes(ext.id)?p.selected.filter(id=>id!==ext.id):[...p.selected,ext.id])}/><button className="extension-name" onClick={()=>p.onDetail(ext.id)}><span className="monogram" style={{background:ext.color}}>{ext.monogram}</span><span><strong title={ext.name}>{ext.name}</strong><small>{ext.publisher}</small></span></button><div className="row-actions"><button className="icon-button" aria-label={`Manage ${ext.name}`} aria-expanded={p.menu===ext.id} onClick={()=>p.onMenu(p.menu===ext.id?null:ext.id)}><MoreHorizontal size={18}/></button>
 {p.menu===ext.id&&<div className="context-menu" role="menu" aria-label={`${ext.name} actions`}><button role="menuitem" onClick={()=>p.onDetail(ext.id)}><Info size={14}/>Details</button><button role="menuitem" onClick={()=>p.onMove(ext.id)}><FolderInput size={14}/>Move to group</button><button role="menuitem" onClick={()=>p.onToggle(ext.id)}><Power size={14}/>{ext.enabled?'Disable':'Enable'}</button>{ext.update&&<button role="menuitem" onClick={()=>p.onUpdate(ext.id)}><ArrowUp size={14}/>Update</button>}<button role="menuitem" onClick={()=>p.onCopy(ext.id)}><Copy size={14}/>Copy ID</button><button role="menuitem" onClick={()=>p.onEditTags(ext.id)}><Tag size={14}/>Edit tags</button></div>}</div></div>
 <div className="card-bottom"><button className={`status ${ext.enabled?'enabled':''}`} aria-label={`${ext.enabled?'Disable':'Enable'} ${ext.name}`} title={ext.enabled?'Disable extension':'Enable extension'} onClick={()=>p.onToggle(ext.id)}>{ext.enabled?'Enabled':'Disabled'}</button><div className="version-actions">{ext.update&&<button className="update" aria-label={`Update ${ext.name}`} title={`Update to ${ext.update}`} onClick={()=>p.onUpdate(ext.id)}><ArrowUp size={13}/></button>}<span className="version">{ext.version}</span></div></div>
 {ext.tags.length>0&&<div className="card-tags">{ext.tags.map(tag=><button key={tag.toLocaleLowerCase()} className="tag-chip" title={`Filter by ${tag}`} onClick={()=>p.onFilterTag(tag)}><Tag size={10} aria-hidden="true" style={{flexShrink:0}}/>{tag}</button>)}</div>}
 </article>)}</div>{section.extensions.length===0&&<div className="group-empty">No extensions</div>}</details>)}{sections.length===0&&<div className="empty">No extensions</div>}</div>
}
